project/base/urls.py
from django.conf.urls import url 
from django.urls import path
from .views import *

app_name = 'base'
 
urlpatterns = [ 
    
    ### ===> URLS do site <===
    ## ====================================================================
    path('', index, name='index'),
    
    path('upload-image/', upload_image, name='upload-image'),

    path('image/<str:pk>/', get_image, name='get-image'),

    path('image/<str:pk>/create-analysis/', create_analysis, name='create-analysis'),

    path('api/delete-analysis/<int:aid>/<int:iid>/', delete_analysis, name="delete-analysis"),

    path('api/update-analysis/<int:aid>/<int:iid>/', update_analysis, name="update-analysis"),

    path('api/delete-image/<int:pk>/', delete_image, name="delete-image"),

    ### ===> URLS da API <===
    ## ====================================================================
    # lista todas as imagens
    path('api/images/', get_images_api, name='get-images-api'),

    # cria imagens com o endereço
    path('api/image/create-image/', create_image_api, name="create-image-api"),

    # retorna dados das imagens com análises
    path('api/image/<int:pk>/', get_image_api, name="get-image-api"),

    # deleta imagens e análises relaciondas
    path('api/delete-image/<int:pk>/', delete_image_api, name="delete-image-api"),

    # cria análise da imagem com id=pk
    path('api/image/<int:pk>/create-analysis/', create_analysis_api, name="create-analysis-api"),

    # deleta análise com id=pk
    path('api/update-analysis/<int:pk>/', update_analysis_api, name="update-analysis-api"),

    # deleta análise com id=pk
    path('api/delete-analysis/<int:pk>/', delete_analysis_api, name="delete-analysis-api"),

    # lista todas as análises
    path('api/analyses/', analyses_list_api, name="analyses-list-api"),
]

project/project/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/base/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
        
    class Meta:
        db_table = "base_image"

class Analysis(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    nome = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nome
        
    class Meta:
        db_table = "base_analysis"

project/base/forms.py
from django import forms
from rest_framework import serializers
from .models import Image, Analysis

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image')

class AnalysisForm(forms.ModelForm):
    image = forms.ModelChoiceField(queryset=Image.objects.all())
    class Meta:
        model = Analysis
        fields = ('nome', 'tipo', 'status')
        

project/base/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http.response import JsonResponse
from django.http import HttpResponse
from django.conf import settings
from django.urls import reverse_lazy
from django.core import serializers

import json

from django.contrib.auth.views import LoginView

from rest_framework.decorators import api_view
from rest_framework.response import Response

from django import forms
from .forms import AnalysisForm, ImageForm
from .models import Analysis, Image

from base.serializers import ImageSerializer, AnalisysSerializer

## Views da API
## ====================================================================
@api_view(['GET'])
def get_images_api(request):
    if request.method == 'GET': 
        images = Image.objects.all()
        serializer = ImageSerializer(images, many=True)
        
        return Response(serializer.data)

@api_view(['POST'])
def create_image_api(request):
    if request.method == 'POST':
        form = ImageForm(request.POST)

        new_image = Image.objects.create(
            title = form.data['title'],
            image = '/images/' + form.data['image']
        )

        new_image.save()

        res = json.loads(serializers.serialize('json', [new_image]))

        return Response(res)

@api_view(['GET'])
def get_image_api(request, pk):
    image = Image.objects.get(id=pk)
    serializer = ImageSerializer(image, many=False)
    
    return Response(serializer.data)

@api_view(['POST'])
def create_analysis_api(request, pk):
    image = Image.objects.get(pk=pk)
    if request.method == 'POST' and image is not None:
        form = AnalysisForm(request.POST)

        status = form.data['status'] == 'true'

        new_analysis = Analysis.objects.create(
            name = form.data['nome'],
            tipo = form.data['tipo'],
            status = status,
            image = image
        )

        new_analysis.save()

        res = json.loads(serializers.serialize('json', [new_analysis]))

        return Response(res)

@api_view(['POST'])
def update_analysis_api(request, pk):
    
    analysis = Analysis.objects.get(pk=pk)

    if request.method == 'POST' and analysis is not None:
        form = AnalysisForm(request.POST, instance=analysis)

        status = form.data['status'] == 'true'

        analysis.name = form.data['nome']
        analysis.tipo = form.data['tipo']
        analysis.status = status
        analysis.save()

        return Response(form.data)

@api_view(['POST'])
def delete_analysis_api(request, pk):
    
    analysis = Analysis.objects.get(pk=pk)

    if request.method == 'POST' and analysis is not None:
        analysis.delete()
        return Response({'menssagem': 'A análise de id: ' + str(pk) + ' foi deletada com sucesso'})

@api_view(['GET'])
def analyses_list_api(request):
    if request.method == 'GET': 
        analysis = Analysis.objects.all()
        serializer = AnalisysSerializer(analysis, many=True)

        return Response(serializer.data)

@api_view(['POST'])
def delete_image_api(request, pk):
    
    image = Image.objects.get(pk=pk)

    if request.method == 'POST' and image is not None:
        image.delete()
        return Response({'menssagem': 'A imagem de id: ' + str(pk) + ' foi deletada com sucesso'})

## Views do site
## ====================================================================
def index(request):
    if request.method == 'GET':
        images = Image.objects.all()
        serialized = ImageSerializer(images, many=True)

        context = {
            'images': serialized.data
        }

        return render(request, 'home.html', context)
    
def upload_image(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            return render(request, 'upload.html', {'form': form, 'img_obj': img_obj})
    else:
        form = ImageForm()
    return render(request, 'upload.html', {'form': form})

def get_image(request, pk):
    image = Image.objects.get(pk=pk)
    image_serialized = ImageSerializer(image, many=False)

    form = AnalysisForm(request.POST)

    analyses = Analysis.objects.all().filter(image=image)
    analyses_serialized = AnalisysSerializer(analyses, many=True)

    context = {
        'image': image_serialized.data,
        'analyses': analyses_serialized.data,
        'form': form
    }

    return render(request, 'image.html', context)

def create_analysis(request, pk):
    image = Image.objects.get(pk=pk)
    if request.method == 'POST':
        form = AnalysisForm(request.POST)

        try:
            status = form.data['status'] == 'on'
        except:
            status = False
    
        new_analysis = Analysis.objects.create(
            nome = form.data['nome'],
            tipo = form.data['tipo'],
            status = status,
            image = image
        )

        new_analysis.save()

        return redirect('/image/' + str(pk) + '/')

def delete_analysis(request, aid, iid):
    
    analysis = Analysis.objects.get(pk=aid)
    analysis.delete()
    
    return redirect('/image/' + str(iid) + '/')

def update_analysis(request, aid, iid):
    
    analysis = Analysis.objects.get(pk=aid)
    image = Image.objects.get(pk=iid)

    if request.method == 'POST' and analysis is not None:
        form = AnalysisForm(request.POST, instance=analysis)

        try:
            status = form.data['status'] == 'on'
        except:
            status = False
    
        analysis.nome = form.data['nome']
        analysis.tipo = form.data['tipo']
        analysis.status = status
        analysis.save()

        return redirect('/image/' + str(iid) + '/')

    else:
        form = AnalysisForm(instance=analysis)

        context = {
            'form': form,
            'aid': aid,
            'iid': iid,
        }

        return render(request, 'analysis.html', context)

def delete_image(request, pk):
    
    image = Image.objects.get(pk=pk)
    image.delete()

    return redirect('/')

project/base/templates/analysis.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center p-3">
    <div class="card border-primary mb-3" style="width: auto;">
        <div class="card-header"><h4>Atualização de análise</h4></div>
        <div class="card-body">
            
            <form action="{% url 'base:update-analysis' aid=aid iid=iid %}" method="post">
                {% csrf_token %}
                <div class="form-group row my-3">
                    {{ form.nome|as_crispy_field }}
                </div>
                <div class="form-group row my-3">
                  {{ form.tipo|as_crispy_field }}
                </div>
                <div class="form-group row my-3">
                  {{ form.status|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/base/templates/create-analysis.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center p-3">
    <div class="card border-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary mt-3">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/base/templates/home.html
{% extends 'main.html' %}

{% block content %}
<div class="justify-content-center row p-3">
  <h2 class="py-3">Imagens</h2>
  <hr>
  {% for data in images %}
  <div class="col-md-4 my-3">
    <div class="card mb-3">
      <div class="card-header col d-flex justify-content-between align-items-center">
        <h4>{{data.title}}</h4>
        <span class="badge bg-primary p-2">{{data.fileExtention}}</span>
      </div>
      <div class="card-body" style="display: flex; justify-content: center; align-items: center;">
        <img src='{{data.image}}' alt="connect" style="max-width:90%;">
      </div>
      <div class="card-body row justify-content-center">
        <div class="col-md-6">
          <a href="{% url 'base:get-image' data.pk %}">
            <button type="button" class="btn btn-outline-primary p-3 mt-1" style="width: 100%;">
              Ver análises
            </button>
          </a>
        </div>
      </div>
      <div class="card-footer text-muted">
        Registro criado em {{data.created_at}}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

project/base/templates/image.html
{% extends 'main.html' %}
{% block content %}

{% load crispy_forms_tags %}

<div class="justify-content-center row p-3">
  <div class="col-md-6 my-3">
    <div class="card mb-3">
      <div class="card-header col d-flex justify-content-between align-items-center">
        <h4>{{image.title}}</h4>
        <span class="badge bg-primary p-2">{{image.fileExtention}}</span>
      </div>
      <div class="card-body" style="display: flex; justify-content: center; align-items: center;">
        <img src='{{image.image}}' alt="connect" style="max-width:90%;">
      </div>
      <div class="card-body row">
        <div class="col-md-6">
          <button type="button" id="analysisModalButton" class="btn btn-outline-primary p-3" style="width: 100%;" data-toggle="modal" data-target="#exampleModalCenter">
            Criar análise
          </button>
        </div>
        <div class="col-md-6">
          <button type="button" id="deleteImageModalButton" class="btn btn-outline-danger p-3" style="width: 100%;" data-toggle="modal" data-target="#exampleModalCenter">
            Apagar imagem
          </button>
        </div>
      </div>
      <div class="card-footer text-muted">
        Registro criado em {{image.created_at}}
      </div>
    </div>
  </div>
  
  <h4 class="py-3">Análises</h4>
  <hr>
  <div class="row py-3">
    <div class="table-wrapper-scroll-y my-custom-scrollbar">
      <table class="table table-bordered table-striped mb-0">
        <thead class="table-primary">
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Tipo</th>
            <th scope="col">Analisado?</th>
            <th scope="col">Data de criação</th>
            <th scope="col">Data de modificação</th>
            <th scope="col">Apagar?</th>
          </tr>
        </thead>
        <tbody>
          {% for analysis in analyses %}
            <tr>
              <th><a href="{% url 'base:update-analysis' aid=analysis.id iid=image.pk %}">{{ analysis.nome }}</a></th>
              <td>{{ analysis.tipo }}</td>
              <td>{{ analysis.status }}</td>
              <td>{{ analysis.created_at }}</td>
              <td>{{ analysis.updated_at }}</td>
              <td>
                <a href="{% url 'base:delete-analysis' aid=analysis.id iid=image.pk %}">
                  <button type="button" class="btn btn-danger">&#128465;</button>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Modal de análise -->
<div class="modal fade" id="analysisModal" tabindex="-1" role="dialog" aria-labelledby="analysisModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Nova análise</h5>
        <button type="button" class="btn btn-danger analysisModalCloseButton" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!-- enctype="multipart/form-data" -->
        <form action="{% url 'base:create-analysis' image.pk %}" method="post">
            {% csrf_token %}
            <div class="form-group row mb-0">
              {{ form.nome|as_crispy_field }}
            </div>
            <div class="form-group row mb-0">
              {{ form.tipo|as_crispy_field }}
            </div>
            <div class="form-group row mb-3">
              {{ form.status|as_crispy_field }}
            </div>
            <button type="submit" class="btn btn-primary">Criar análise</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal de análise -->
<div class="modal fade" id="deleteImageModal" tabindex="-1" role="dialog" aria-labelledby="deleteImageModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Deseja deletar a imagem "{{image.title}}"</h5>
        <button type="button" class="btn btn-danger deleteImageModalCloseButton" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <a href="{% url 'base:delete-image' image.pk %}">
          <button type="button" class="btn btn-outline-danger">Confirmar exclusão</button>
        </a>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $("#analysisModalButton").click(function(){
        $("#analysisModal").modal('show');
    });
  });

  $(document).ready(function(){
    $(".analysisModalCloseButton").click(function(){
        $("#analysisModal").modal('hide');
    });
  });

  $(document).ready(function(){
    $("#deleteImageModalButton").click(function(){
        $("#deleteImageModal").modal('show');
    });
  });

  $(document).ready(function(){
    $(".deleteImageModalCloseButton").click(function(){
        $("#deleteImageModal").modal('hide');
    });
  });
</script>
{% endblock content %}

project/base/templates/login.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center p-3">
    <div class="card border-primary mb-3" style="max-width: 20rem;">
        <div class="card-header"><h4>Login</h4></div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary mt-3">Login</button>
            </form>
            <p>Don't have an account? <a href="#">Register</a></p>
        </div>
    </div>
</div>
{% endblock content %}

project/base/templates/main.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://bootswatch.com/5/minty/bootstrap.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>Gestão de imagens</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <div class="container-fluid row justify-content-between" style="margin: auto;">  
        <div class="col-md-3 d-flex justify-content-center align-items-center">
          <a class="navbar-brand text-center" href="/">Gestão de Imagens</a>
        </div>     
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse col-md-3" id="navbarColor02">          
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="/">
                <button type="button" class="btn btn-danger p-3" style="width: 100%;">
                  Home
                </button>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/upload-image/">
                <button type="button" class="btn btn-secondary p-3" style="width: 100%;">
                  Cadastro de imagens
                </button>
              </a>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
</body>
<script>
  
</script>
</html>

project/base/templates/upload.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center p-3">
    <div class="card border-primary mb-3" style="width: auto;">
        <div class="card-header"><h4>Cadastro de imagem</h4></div>
        <div class="card-body">
            
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row my-3">
                    {{ form.title|as_crispy_field }}
                </div>
                <div class="form-group row my-3">
                    {{ form.image|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
            {% if img_obj %}
                <h3>Upload feito: {{img_obj.title}}</h3>
                <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}